# Generated by Django 2.2.7 on 2019-12-01 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_customuser_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.CustomUser')),
            ],
        ),
    ]
