# Generated by Django 2.2.7 on 2019-12-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20191201_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='body',
            field=models.CharField(max_length=250),
        ),
    ]
